Moved all WorldEdit-related code into TerrainBackup.  This class is only used when WorldEdit is detected.  Fixes a problem with NoClassDefFoundError being thrown if WorldEdit is not installed.