No longer including com.sk89q.util.StringUtil - placed an implementation of getLevenshteinDistance() in ChessUtils.  (It's the same function, which comes from the Apache Jakarta Commons project anyway).  Should solve a problem with a NoSuchMethodError sometimes being thrown when trying to call it.